### ISSUE TITLE
FileBox with type UUID rejection with GitterPuppet

### ISSUE THREAD

**Issue by huan** [wechaty/friday#107]
```
16:04:58 VERB Room say(FileBox#Uuid<message-6373229433108030603-image-normal.jpg>, )
16:04:59 VERB Message static load(7767906334958100053)
16:04:59 VERB Message constructor(7767906334958100053) for class WechatifiedMessageImpl
16:04:59 VERB Message ready()
16:04:59 VERB PuppetMessageMixin messagePayload(7767906334958100053)
16:04:59 VERB PuppetService messageRawPayload(7767906334958100053)
16:04:59 VERB Room ready()
16:04:59 VERB Message static load(3154338781840670693)
16:04:59 VERB Message constructor(3154338781840670693) for class WechatifiedMessageImpl
16:04:59 VERB Message ready()
16:04:59 VERB PuppetMessageMixin messagePayload(3154338781840670693)
16:04:59 VERB PuppetService messageRawPayload(3154338781840670693)
16:04:59 VERB Room ready()
16:04:59 VERB Message static load(2500017943533935764)
16:04:59 VERB Message constructor(2500017943533935764) for class WechatifiedMessageImpl
16:04:59 VERB Message ready()
16:04:59 VERB PuppetMessageMixin messagePayload(2500017943533935764)
16:04:59 VERB PuppetService messageRawPayload(2500017943533935764)
16:04:59 VERB Room ready()
16:05:00 ERR Config ###########################
16:05:00 ERR Config unhandledRejection: Error: need to call FileBox.setUuidLoader() to set UUID loader first.
    at FileBox.toStream (file:///home/friday/git/friday/node_modules/file-box/dist/esm/src/file-box.js:467:27)
    at FileBox.pipe (file:///home/friday/git/friday/node_modules/file-box/dist/esm/src/file-box.js:625:14)
    at FileBox.toBuffer (file:///home/friday/git/friday/node_modules/file-box/dist/esm/src/file-box.js:589:14)
    at PuppetGitter.messageSendFile (file:///home/friday/git/friday/node_modules/wechaty-puppet-gitter/dist/esm/src/puppet-gitter.js:339:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///home/friday/git/friday/node_modules/wechaty/dist/esm/src/interface/sayable.js:49:17
    at async WechatifiedUserClass.say (file:///home/friday/git/friday/node_modules/wechaty/dist/esm/src/user/room.js:351:21)
    at async WechatyImpl.<anonymous> (file:///home/friday/git/friday/dist/src/cross-puppet.js:64:21) [object Promise]
```

**Comment by huan** [comment]
Fix by the latest commit.
