### ISSUE TITLE
Error: conversationId: 696864249 is neither QQ_USER_TYPE nor QQ_GROUP_TYPE

### ISSUE THREAD

**Issue by huan** [wechaty/friday#108]
```
15:16:29 VERB Room say([Huan (李卓桓) @ WeChat]: 开会啦, )
15:16:29 ERR Config ###########################
15:16:29 ERR Config Wechaty unhandledRejection: Error: conversationId: 696864249 is neither QQ_USER_TYPE nor QQ_GROUP_TYPE
    at PuppetOICQ.messageSendText (file:///home/friday/git/friday/node_modules/wechaty-puppet-oicq/dist/esm/src/puppet-oicq.js:189:19)
    at WechatifiedUserClass.say (file:///home/friday/git/friday/node_modules/wechaty/dist/esm/src/user/room.js:368:47)
    at WechatyImpl.<anonymous> (file:///home/friday/git/friday/dist/src/cross-puppet.js:59:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) [object Promise]
15:16:29 ERR Config ###########################
15:16:29 ERR Config process.on(unhandledRejection) promise.catch(conversationId: 696864249 is neither QQ_USER_TYPE nor QQ_GROUP_TYPE)
Config Error: conversationId: 696864249 is neither QQ_USER_TYPE nor QQ_GROUP_TYPE
    at PuppetOICQ.messageSendText (file:///home/friday/git/friday/node_modules/wechaty-puppet-oicq/dist/esm/src/puppet-oicq.js:189:19)
    at WechatifiedUserClass.say (file:///home/friday/git/friday/node_modules/wechaty/dist/esm/src/user/room.js:368:47)
    at WechatyImpl.<anonymous> (file:///home/friday/git/friday/dist/src/cross-puppet.js:59:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:2091744) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
```

**Comment by huan** [comment]
```
17:41:42 VERB Message mentionList()
17:41:42 VERB Room say(`Huan (李卓桓) @ WeChat`: 239, )
17:41:42 VERB PuppetLoginMixin get currentUserId()
17:41:42 VERB WechatyPluginContrib mapMessage(Message#Text[🗣Contact<Huan (李卓桓)>@👥Room<BOT5 Club Open Forum - BFOF 2021>]  239)
17:41:42 VERB PuppetLoginMixin get currentUserId()
17:41:42 VERB WechatyPluginContrib normalizeMappedMessageList(undefined, Message#Text[🗣Contact<Huan (李卓桓)>@👥Room<BOT5 Club Open Forum - BFOF 2021>]       239)
17:41:42 VERB PuppetLoginMixin get currentUserId()
17:41:42 VERB PuppetRoomMemberMixin roomMemberPayload(roomId=18825797159@chatroom, memberId=lizhuohuan)
17:41:42 VERB PuppetLoginMixin get currentUserId()
17:41:42 INFO StarterBot Message#Text[🗣Contact<Huan (李卓桓)>@👥Room<BOT5 Club Open Forum - BFOF 2021>] 239
17:41:42 VERB PuppetLoginMixin get currentUserId()
17:41:42 VERB PuppetLoginMixin get currentUserId()
17:41:42 VERB Room topic()
17:41:42 VERB WechatyPluginContrib stringMatcher() matchString(239)
17:41:42 VERB Room topic()
17:41:42 VERB Room topic()
17:41:42 VERB PuppetLoginMixin get currentUserId()
17:41:42 VERB WechatyPluginContrib normalizeMappedMessageList(["[Huan (李卓桓)@BOT5]: 239"], Message#Text[🗣Contact<Huan (李卓桓)>@👥Room<BOT5 Club Open Forum - BFOF 2021>]   239)
17:41:42 VERB WechatyPluginContrib roomTalker(["[Huan (李卓桓)@BOT5]: 239"])
17:41:42 VERB WechatyPluginContrib roomTalker() talkRoom(Room<BOT5.Club Open Forum - Year 2020>,Room<BOT5.Club Open Forum - Year 2019>, , )
17:41:42 VERB Room say([Huan (李卓桓)@BOT5]: 239, )
17:41:42 VERB PuppetService messageSend(18095776930@chatroom, [Huan (李卓桓)@BOT5]: 239)
17:41:42 VERB Message static load(1834456351161990131)
17:41:42 VERB Message constructor(1834456351161990131) for class WechatifiedMessageImpl
17:41:42 VERB Message ready()
17:41:42 VERB PuppetMessageMixin messagePayload(1834456351161990131)
17:41:42 VERB PuppetService messageRawPayload(1834456351161990131)
17:41:42 VERB Room ready()
17:41:43 VERB Room say([Huan (李卓桓) @ WeChat]: 239, )
17:41:43 ERR Config ###########################
17:41:43 ERR Config Wechaty unhandledRejection: Error: conversationId: 696864249 is neither QQ_USER_TYPE nor QQ_GROUP_TYPE
    at PuppetOICQ.messageSendText (file:///home/friday/git/friday/node_modules/wechaty-puppet-oicq/dist/esm/src/puppet-oicq.js:189:19)
    at WechatifiedUserClass.say (file:///home/friday/git/friday/node_modules/wechaty/dist/esm/src/user/room.js:368:47)
    at WechatyImpl.<anonymous> (file:///home/friday/git/friday/dist/src/cross-puppet.js:59:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) [object Promise]
17:41:43 ERR Config ###########################
17:41:43 ERR Config process.on(unhandledRejection) promise.catch(conversationId: 696864249 is neither QQ_USER_TYPE nor QQ_GROUP_TYPE)
Config Error: conversationId: 696864249 is neither QQ_USER_TYPE nor QQ_GROUP_TYPE
    at PuppetOICQ.messageSendText (file:///home/friday/git/friday/node_modules/wechaty-puppet-oicq/dist/esm/src/puppet-oicq.js:189:19)
    at WechatifiedUserClass.say (file:///home/friday/git/friday/node_modules/wechaty/dist/esm/src/user/room.js:368:47)
    at WechatyImpl.<anonymous> (file:///home/friday/git/friday/dist/src/cross-puppet.js:59:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:2098457) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
17:41:43 VERB Message static load(617e64d73f09d857364684c1)
17:41:43 VERB Message constructor(617e64d73f09d857364684c1) for class WechatifiedMessageImpl
17:41:43 VERB Message ready()
17:41:43 VERB PuppetMessageMixin messagePayload(617e64d73f09d857364684c1)
17:41:43 VERB PuppetGitter messageRawPayload(617e64d73f09d857364684c1)
17:41:43 VERB Room ready()
17:41:43 VERB PuppetLoginMixin get currentUserId()
17:41:43 VERB DingDong isMatchConfig() isMatch(Message#Text[🗣Contact<Mike BO>@👥Room<wechaty/wechaty>]  `Huan (李卓桓) @ WeChat`: 239)
17:41:43 VERB PuppetLoginMixin get currentUserId()
17:41:43 INFO WechatyPluginContrib EventLogger message: Message#Text[🗣Contact<Mike BO>@👥Room<wechaty/wechaty>] `Huan (李卓桓) @ WeChat`: 239
17:41:43 VERB PuppetLoginMixin get currentUserId()
17:41:43 VERB PuppetLoginMixin get currentUserId()
17:41:43 VERB PuppetLoginMixin get currentUserId()
17:41:43 VERB PuppetLoginMixin get currentUserId()
17:41:43 VERB Message mentionList()
17:41:43 VERB WechatyPluginContrib stringMatcher() matchString(`Huan (李卓桓) @ WeChat`: 239)
```

**Comment by huan** [comment]
Fixed. 

The QQ Room id should be `group_` prefixed.
