### ISSUE TITLE
BUG: Use `room id` as `contact id` by mistake

### ISSUE THREAD

**Issue by huan** [wechaty/friday#123]
`R:10855009180534640` is a room id ("Wechaty Developers' Home 5"), but according to the log below, the program uses it as a contact id.

to be investigated.

```
11:23:50 VERB PuppetMessageMixin messagePayload(1036562)
11:23:51 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload(len:51)})
11:23:51 INFO WechatyPluginContrib EventLoggerPlugin() heartbeat: ["onGrpcStreamEvent(EVENT_TYPE_DIRTY)"]
11:23:51 VERB PuppetService onDirty(Room<3>, R:10855009180534640)
11:23:51 VERB PuppetCacheMixin onDirty(Room<3>, R:10855009180534640)
11:23:51 VERB PuppetRoomMixin roomPayload(R:10855009180534640)
11:23:51 VERB PuppetService roomRawPayload(R:10855009180534640)
11:23:51 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_ROOM_LEAVE(20), payload(len:126)})
11:23:51 INFO WechatyPluginContrib EventLoggerPlugin() heartbeat: ["onGrpcStreamEvent(EVENT_TYPE_ROOM_LEAVE)"]
11:23:51 VERB PuppetRoomMixin roomPayloadDirty(R:10855009180534640)
11:23:51 VERB PuppetCacheMixin __dirtyPayloadAwait(Room<3>, R:10855009180534640)
11:23:51 VERB PuppetService dirtyPayload(3, R:10855009180534640)
11:23:51 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload(len:51)})
11:23:51 INFO WechatyPluginContrib EventLoggerPlugin() heartbeat: ["onGrpcStreamEvent(EVENT_TYPE_DIRTY)"]
11:23:51 VERB PuppetService onDirty(Room<3>, R:10855009180534640)
11:23:51 VERB PuppetCacheMixin onDirty(Room<3>, R:10855009180534640)
11:23:51 VERB PuppetRoomMixin roomPayload(R:10855009180534640)
11:23:51 VERB PuppetService roomRawPayload(R:10855009180534640)
11:23:51 VERB PuppetRoomMemberMixin roomMemberPayloadDirty(R:10855009180534640)
11:23:51 VERB PuppetCacheMixin __dirtyPayloadAwait(RoomMember<4>, R:10855009180534640)
11:23:51 VERB PuppetService dirtyPayload(4, R:10855009180534640)
11:23:51 VERB PuppetService roomMemberList(R:10855009180534640)
11:23:51 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload(len:51)})
11:23:51 INFO WechatyPluginContrib EventLoggerPlugin() heartbeat: ["onGrpcStreamEvent(EVENT_TYPE_DIRTY)"]
11:23:51 VERB PuppetService contactRawPayload(R:10855009180534640)
11:23:51 VERB PuppetService onDirty(RoomMember<4>, R:10855009180534640)
11:23:51 VERB PuppetCacheMixin onDirty(RoomMember<4>, R:10855009180534640)
11:23:51 VERB PuppetRoomMixin roomPayload(R:10855009180534640)
11:23:51 VERB PuppetService roomMemberList(R:10855009180534640)
11:23:51 VERB PuppetService roomMemberList(R:10855009180534640)
11:23:51 INFO WechatyPluginContrib EventLoggerPlugin() error: [{"code":13,"details":"contactPayload() can not get contact payload by wrong id: R:10855009
180534640","message":"13 INTERNAL: contactPayload() can not get contact payload by wrong id: R:10855009180534640","name":"Error","stack":"Error: 13 INTER
NAL: contactPayload() can not get contact payload by wrong id: R:10855009180534640\n    at callErrorFromStatus (/home/friday/git/friday/node_modules/@grp
c/grpc-js/src/call.ts:81:17)\n    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client.ts:356:55)\n    at Object.onRe
ceiveStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)\n    at Object.onReceiveStatus (/home/friday/git/frida
y/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)\n    at /home/friday/git/friday/node_modules/@grpc/grpc-js/src/resolving-call.ts:110:24\n
    at processTicksAndRejections (node:internal/process/task_queues:78:11)\nfor call at\n    at ServiceClientImpl.makeUnaryRequest (/home/friday/git/frid
ay/node_modules/@grpc/grpc-js/src/client.ts:326:30)\n    at ServiceClientImpl.contactPayload (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/make
-client.ts:189:15)\n    at node:internal/util:360:7\n    at new Promise (<anonymous>)\n    at bound  (node:internal/util:346:12)\n    at PuppetService.co
ntactRawPayload (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:663:6)\n    at PuppetService.contactPayl
oad (file:///home/friday/git/friday/node_modules/wechaty-puppet/src/mixins/contact-mixin.ts:298:26)\n    at WechatifiedUserClass.ready (file:///home/frid
ay/git/friday/node_modules/wechaty/src/user-modules/contact.ts:699:22)\n    at Function.find (file:///home/friday/git/friday/node_modules/wechaty/src/use
r-modules/contact.ts:114:9)\n    at PuppetService.<anonymous> (file:///home/friday/git/friday/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:441
:37)"}]
GError: 13 INTERNAL: contactPayload() can not get contact payload by wrong id: R:10855009180534640
    at callErrorFromStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client.ts:356:55)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
    at /home/friday/git/friday/node_modules/@grpc/grpc-js/src/resolving-call.ts:110:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client.ts:326:30)
    at ServiceClientImpl.contactPayload (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:346:12)
    at PuppetService.contactRawPayload (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:663:6)
    at PuppetService.contactPayload (file:///home/friday/git/friday/node_modules/wechaty-puppet/src/mixins/contact-mixin.ts:298:26)
    at WechatifiedUserClass.ready (file:///home/friday/git/friday/node_modules/wechaty/src/user-modules/contact.ts:699:22)
    at Function.find (file:///home/friday/git/friday/node_modules/wechaty/src/user-modules/contact.ts:114:9)
    at PuppetService.<anonymous> (file:///home/friday/git/friday/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:441:37) {
  code: 13,
  details: 'contactPayload() can not get contact payload by wrong id: R:10855009180534640'
}
11:23:51 ERR on-error onError(Error: 13 INTERNAL: contactPayload() can not get contact payload by wrong id: R:10855009180534640)
GError: 13 INTERNAL: contactPayload() can not get contact payload by wrong id: R:10855009180534640
    at callErrorFromStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client.ts:356:55)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
    at /home/friday/git/friday/node_modules/@grpc/grpc-js/src/resolving-call.ts:110:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client.ts:326:30)
    at ServiceClientImpl.contactPayload (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:346:12)
    at PuppetService.contactRawPayload (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:663:6)
    at PuppetService.contactPayload (file:///home/friday/git/friday/node_modules/wechaty-puppet/src/mixins/contact-mixin.ts:298:26)
    at WechatifiedUserClass.ready (file:///home/friday/git/friday/node_modules/wechaty/src/user-modules/contact.ts:699:22)
    at Function.find (file:///home/friday/git/friday/node_modules/wechaty/src/user-modules/contact.ts:114:9)
    at PuppetService.<anonymous> (file:///home/friday/git/friday/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:441:37) {
  code: 13,
  details: 'contactPayload() can not get contact payload by wrong id: R:10855009180534640'
}
Error: 13 INTERNAL: contactPayload() can not get contact payload by wrong id: R:10855009180534640
    at callErrorFromStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client.ts:356:55)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
    at /home/friday/git/friday/node_modules/@grpc/grpc-js/src/resolving-call.ts:110:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/client.ts:326:30)
    at ServiceClientImpl.contactPayload (/home/friday/git/friday/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:346:12)
    at PuppetService.contactRawPayload (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:663:6)
    at PuppetService.contactPayload (file:///home/friday/git/friday/node_modules/wechaty-puppet/src/mixins/contact-mixin.ts:298:26)
    at WechatifiedUserClass.ready (file:///home/friday/git/friday/node_modules/wechaty/src/user-modules/contact.ts:699:22)
    at Function.find (file:///home/friday/git/friday/node_modules/wechaty/src/user-modules/contact.ts:114:9)
    at PuppetService.<anonymous> (file:///home/friday/git/friday/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:441:37)
```

**Comment by huan** [comment]
Might  related to https://github.com/wechaty/wechaty/issues/2410
