### ISSUE TITLE
TypeError: request.setMentonalIdsList is not a function

### ISSUE THREAD

**Issue by huan** [wechaty/friday#92]
```
23:05:59 VERB PuppetService messageSend(18131996049@chatroom, Der! I just got online!
Friday.BOT v0.11.11)
23:05:59 VERB ContactSelf name()
23:05:59 VERB ContactSelf name()
23:05:59 INFO IoClient Friday BOT logged in
23:05:59 VERB Io send() without a connected websocket, eventBuffer.length = 1
23:05:59 VERB Room ready()
23:05:59 VERB Puppet roomPayload(24980472405@chatroom)
23:05:59 VERB PuppetService roomRawPayload(24980472405@chatroom)
23:05:59 VERB FlashStore get(24980472405@chatroom)
23:05:59 ERR Config ###########################
23:05:59 ERR Config unhandledRejection: TypeError: request.setMentonalIdsList is not a function
    at PuppetService.messageSendText (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:547:21)
    at WechatifiedRoom.say (file:///home/friday/git/friday/node_modules/wechaty/dist/esm/src/user/room.js:402:47)
    at Wechaty.<anonymous> (file:///home/friday/git/friday/dist/src/friday/setup-finis.js:15:60)
    at Wechaty.emit (events.js:388:22)
    at Wechaty.emit (domain.js:470:12)
    at PuppetService.<anonymous> (file:///home/friday/git/friday/node_modules/wechaty/dist/esm/src/wechaty.js:295:34) [object Promise]
```

**Comment by huan** [comment]
We should be careful when working with gRPC definitions.

Though this name change (`setMentonalIdsList` -> `setMentionalIdsList`) will not affect the network communication (thanks gRPC!), however, it still affects our program if the version is a mismatch by mistake.
